# Generated by Django 2.1.5 on 2020-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20180530_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(verbose_name='Registration Date'),
        ),
    ]
