# Generated by Django 2.1.5 on 2020-08-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_auto_20200812_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='dob',
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(verbose_name=('Registration Date',)),
        ),
    ]
